name: Feature Request
description: Suggest an idea
title: "<title>"
labels: "t: enhancement"
body:
  - type: markdown
    attributes:
      value: |
        * Please search to see if an issue already exists for the bug you encountered.
  - type: textarea
    attributes:
      label: Problem Description
      description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have searched the existing issues for a bug report that matches the one I want to file, without success.
        required: true
