name: Build documentation

on:
  pull_request:
  push:
  workflow_dispatch:
    # Allow to run manually

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container: ghcr.io/sagemath/sage/sage-docker-ubuntu-focal-standard-with-targets:dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          apt-get update && apt-get install -y zip
          # Reuse built SAGE_LOCAL contained in the Docker image
          ./bootstrap
          ./configure --enable-build-as-root --prefix=/sage/local --with-sage-venv --enable-download-from-upstream-url

      - name: Build
        run: make doc-html
        env:
          MAKE: make -j2
          SAGE_NUM_THREADS: 2

      - name: Copy docs
        run: |
          # For some reason the deploy step below cannot find /sage/...
          # So copy everything from there to local folder
          # We also need to replace the symlinks because netlify is not following them
          mkdir -p ./docs
          cp -r -L /sage/local/share/doc/sage/html/en/* ./docs
          # Zip everything for increased performance
          zip -r docs.zip docs

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs.zip
